version: "3"

services:
  webscraper:
    build: .
    container_name: webscraper
    restart: unless-stopped
    ports:
      - 8000:8000
    command: gunicorn app:app --bind 0.0.0.0:8000 --workers 4